import { chromium } from 'playwright'
const base = process.argv[2], out = process.argv[3]
const browser = await chromium.launch({ channel: 'chrome', headless: true })
const page = await browser.newPage({ viewport: { width: 1400, height: 900 }, deviceScaleFactor: 1 })
await page.goto(`${base}/#/live`, { waitUntil: 'commit' })
await page.waitForFunction(() => /\d+ fps/.test(document.querySelector('nav')?.textContent || ''), null, { timeout: 20000 })
await page.waitForTimeout(1500)
await page.locator('.panel:has(h3:has-text("Photo")) select').first().selectOption('focusfine'); await page.waitForTimeout(300)
await page.locator('aside').evaluate((el) => (el.scrollTop = 0))
await page.screenshot({ path: `${out}/live-top.png` })
await page.locator('aside').evaluate((el) => (el.scrollTop = el.scrollHeight))
await page.screenshot({ path: `${out}/live-bottom.png` })
// make some gallery items quickly
await page.locator('.panel:has(h3:has-text("Photo")) select').first().selectOption('single'); await page.click('button:has-text("Take photo")')
await page.waitForFunction(() => /saved "Photo/.test(document.querySelector('main')?.textContent || ''), null, { timeout: 30000 })
await page.locator('.panel:has(h3:has-text("Photo")) select').first().selectOption('focus'); await page.click('button:has-text("Take photo")')
await page.waitForFunction(() => /saved "Focus stack/.test(document.querySelector('main')?.textContent || ''), null, { timeout: 60000 })
await page.locator('.panel:has(h3:has-text("Photo")) select').first().selectOption('raw'); await page.click('button:has-text("Take photo")')
await page.waitForFunction(() => /saved "RAW/.test(document.querySelector('main')?.textContent || ''), null, { timeout: 60000 })
await page.goto(`${base}/#/gallery`, { waitUntil: 'commit' }); await page.waitForTimeout(1500)
await page.screenshot({ path: `${out}/gallery.png` })
await page.goto(`${base}/#/calibrate`, { waitUntil: 'commit' }); await page.waitForTimeout(1500)
await page.screenshot({ path: `${out}/calibrate.png` })
await page.goto(`${base}/#/settings`, { waitUntil: 'commit' }); await page.waitForTimeout(1000)
await page.screenshot({ path: `${out}/settings.png`, fullPage: true })
await browser.close()
